### ISSUE TITLE
Scoreboard "show all" button doesn't do anything

### ISSUE THREAD

**Issue by dippas** [Filnor/RankOverflow#14] opened 2019-10-06 03:35 UTC
Whenever I come to https://rankoverflow.philnet.ch/scoreboard , now its only showing the top 3(before was showing top 10) and then the "show all" button doesn't do anything, not even throwing any console error

**Comment by Filnor** [comment] 2019-10-31 14:36
Seems I missed either to update the bot that sends the data to the scoreboard or the recieving endpoint has a bug. I'll look into it.

**Comment by Filnor** [comment] 2019-11-19 23:54
Turns out I forgot to put in the `fkey` on the bot side. It's fixed now and runs as intended.

**Closed as completed by Filnor** 2019-11-19 23:54 UTC
Labels: bug, scoreboard
